//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementPortal_v0._8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmployeeManagementAppEntities : DbContext
    {
        public EmployeeManagementAppEntities()
            : base("name=EmployeeManagementAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual int DeleteUser(Nullable<int> ip_ID)
        {
            var ip_IDParameter = ip_ID.HasValue ?
                new ObjectParameter("ip_ID", ip_ID) :
                new ObjectParameter("ip_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteUser", ip_IDParameter);
        }
    
        public virtual ObjectResult<GetUserByUID_Result> GetUserByUID(Nullable<int> ip_ID)
        {
            var ip_IDParameter = ip_ID.HasValue ?
                new ObjectParameter("ip_ID", ip_ID) :
                new ObjectParameter("ip_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUserByUID_Result>("GetUserByUID", ip_IDParameter);
        }
    
        public virtual ObjectResult<GetUsers_Result> GetUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_Result>("GetUsers");
        }
    
        public virtual int InsertUser(string ip_UserName, string ip_Password, string ip_Role, string ip_Image)
        {
            var ip_UserNameParameter = ip_UserName != null ?
                new ObjectParameter("ip_UserName", ip_UserName) :
                new ObjectParameter("ip_UserName", typeof(string));
    
            var ip_PasswordParameter = ip_Password != null ?
                new ObjectParameter("ip_Password", ip_Password) :
                new ObjectParameter("ip_Password", typeof(string));
    
            var ip_RoleParameter = ip_Role != null ?
                new ObjectParameter("ip_Role", ip_Role) :
                new ObjectParameter("ip_Role", typeof(string));
    
            var ip_ImageParameter = ip_Image != null ?
                new ObjectParameter("ip_Image", ip_Image) :
                new ObjectParameter("ip_Image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertUser", ip_UserNameParameter, ip_PasswordParameter, ip_RoleParameter, ip_ImageParameter);
        }
    
        public virtual int UpdateUser(string ip_UserName, string ip_Password, string ip_Role, string ip_Image, Nullable<int> ip_Id)
        {
            var ip_UserNameParameter = ip_UserName != null ?
                new ObjectParameter("ip_UserName", ip_UserName) :
                new ObjectParameter("ip_UserName", typeof(string));
    
            var ip_PasswordParameter = ip_Password != null ?
                new ObjectParameter("ip_Password", ip_Password) :
                new ObjectParameter("ip_Password", typeof(string));
    
            var ip_RoleParameter = ip_Role != null ?
                new ObjectParameter("ip_Role", ip_Role) :
                new ObjectParameter("ip_Role", typeof(string));
    
            var ip_ImageParameter = ip_Image != null ?
                new ObjectParameter("ip_Image", ip_Image) :
                new ObjectParameter("ip_Image", typeof(string));
    
            var ip_IdParameter = ip_Id.HasValue ?
                new ObjectParameter("ip_Id", ip_Id) :
                new ObjectParameter("ip_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateUser", ip_UserNameParameter, ip_PasswordParameter, ip_RoleParameter, ip_ImageParameter, ip_IdParameter);
        }
    }
}
