//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementPortal_v0._8.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class User
    {
        public int Id { get; set; }
        
        //[Required (AllowEmptyStrings =false, ErrorMessage ="Username cannot be Empty" ) ]
        public string UserName { get; set; }

        //[Required (AllowEmptyStrings =false, ErrorMessage = "Password cannot be Empty")]
        [DataType("Password")]
        public string Password { get; set; }
        public string Role { get; set; }
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public string ErrorMessage { get; set; }
    }
}
